### ISSUE TITLE
Error: AWS Designer: Cannot convert the template because of an error:: duplicated mapping key at line 900, column 38: ... Name: ProvideApproval

### ISSUE THREAD

**Issue by rahuljain81** [aws-samples/twelve-factor-app-ecs-blog#1]
Hi,

When I uploading the yml file in AWS CloudFormation, Designer is giving below error:-

9/12/2021, 11:53:51 AM - Cannot convert the template because of an error:: duplicated mapping key at line 900, column 38: ... Name: ProvideApproval ^

Can you please check and guide how to fix the issue?

**Comment by sushanthmangalore** [comment]
Thank you for bringing this to my attention. This has been resolved with the latest version in the main branch.
