### ISSUE TITLE
Code Pipeline Issue: Invalid action configuration The AWS ECS container twelve-factor-app-service does not exist

### ISSUE THREAD

**Issue by rahuljain81** [aws-samples/twelve-factor-app-ecs-blog#2]
Hello,

I am facing issue during code pipeline.
I am using default code.

![image](https://user-images.githubusercontent.com/17906192/132976814-0596c106-c39d-468e-96c2-9d73e061c47f.png)

**Comment by sushanthmangalore** [comment]
Thank you for bringing this to my attention. This has been resolved with the latest version in the main branch.
